---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: gce-staging-services-1
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq
  releaseName: redis
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: true
